repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest stable version
    hooks:
      - id: black
        args: [ --line-length=88 ]  # You can set this to 120 if you prefer

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [ --profile=black ]  # Ensures compatibility with Black

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1  # Use the latest stable version
    hooks:
      - id: flake8
        args:
          - --max-line-length=88  # Same as Black (change to 120 if you prefer)
          - --extend-ignore=E203, W503  # Ignore rules that conflict with Black