repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1  # Always replace with the latest tag available
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
