name: Build and Release

on:
  push:
    paths:
      - 'rgg_save_tool.py'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile rgg_save_tool.py

      - name: List Artifacts
        run: ls ./dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rgg_save_tool-${{ matrix.os }}
          path: dist/rgg_save_tool*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: List files in dist (Debug)
        run: |
          echo "Listing files in ./dist/"
          ls -la ./dist/
          echo "Confirming file existence directly"
          ls -la ${{ github.workspace }}/dist/rgg_save_tool*

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/rgg_save_tool-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
