name: Build and Release

on:
  push:
    paths:
      - 'rgg_save_tool.py'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile rgg_save_tool.py

      - name: List Artifacts
        run: ls ./dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rgg_save_tool-${{ matrix.os }}
          path: dist/rgg_save_tool*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Determine Last Tag
        id: last-tag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "none")
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV

      - name: Generate New Tag
        id: new-tag
        run: |
          HASH=$(git rev-parse --short HEAD)
          if [ "${{ env.LAST_TAG }}" = "none" ]; then
            TAG_NAME="v1.0-${HASH}"
          else
            TAG_NAME="${{ env.LAST_TAG }}-${HASH}"
          fi
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Get Commits Since Last Tag
        id: commits
        run: |
          if [ "${{ env.LAST_TAG }}" != "none" ]; then
            COMMITS=$(git log ${{ env.LAST_TAG }}..HEAD --oneline)
          else
            COMMITS=$(git log --oneline)
          fi
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: List files in dist (Debug)
        run: |
          echo "Listing files in ./dist/"
          ls -la ./dist/
          echo "Confirming file existence directly"
          ls -la ${{ github.workspace }}/dist/rgg_save_tool*

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/rgg_save_tool-*
          body: |
            ### Commits Since Last Release:
            ${{ env.COMMITS }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
